// templates/svelte/App.svelte
<script>
  export let name; 
</script>


<div class="main">
  <h1>This is my Microfrontend {name}!</h1>
  <img src="https://raw.githubusercontent.com/fiorelorenzo/svelte-splide/HEAD/images/svelte-logo.png" alt='logo svelte'/>
</div>

<style>
  :global(body) {
    background-color:  rgb(32,35,42);
    color: white;
  }
  .main {
   
    display: flex;
    flex-direction: column;
   justify-content: center;
   align-items: center;
    
  }
  h1 {
    font-size: 50px;
    
}
img {
    width: 30vw;
    height: 50vh;
    
   
}
</style>

// templates/vue/App.vue
<script setup>
// import { RouterLink, RouterView } from 'vue-router'

</script>

<template>
  <div>
    <h1>This is my Microfrontend Vue!</h1>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
  </div>
</template>

<style >
div {
    display: column;
    justify-content: center;
    align-content: center;
}
h1 {
    text-align: center;
    font-size: 50px;
    color:rgb(247,248,250);
}
img {
    width: 50vw;
    height: 50vh;
    text-align: center;
    margin-left: 25%;
}
body{
    background-color: rgb(52,73,94); 
}
</style>
