// templates/vue/App.vue
<script setup>
// import { RouterLink, RouterView } from 'vue-router'

</script>

<template>
  <div>
    <h1>This is my Microfrontend Vue!</h1>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
  </div>
</template>

<style >
div {
    display: column;
    justify-content: center;
    align-content: center;
}
h1 {
    text-align: center;
    font-size: 50px;
    color:rgb(247,248,250);
}
img {
    width: 50vw;
    height: 50vh;
    text-align: center;
    margin-left: 25%;
}
body{
    background-color: rgb(52,73,94); 
}
</style>

// templates/angular/app.component.ts
import { Component } from '@angular/core';

const component = require('./app.component.html');
const style = require('./app.component.css')

@Component({
  selector: 'app-angular',
  template: component.default,
  styleUrls: style.default
 
})
export class AppComponent {
  title = 'appangular';
}

<style>
    *{
        margin:0;
        padding:0;
        box-sizing: border-box;
    }
    div {
    display: column;
    justify-content: center;
    align-content: center;
   }
  img {
    width: 50vw;
    height: 60vh;
    text-align: center;
    margin-left: 25%;
  }
  h1 {
    text-align: center;
    font-size: 50px;
    color: gray;
  }
  body {
    background-color: rgb(247, 248, 250);
  }
</style>
<div>
  <h1>This is my Microfrontend Angular</h1>
  <img
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
</div>
